# Generated by Django 3.1.5 on 2021-01-17 22:07

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=30)),
                ('student_surname', models.CharField(max_length=30)),
                ('student_number', models.IntegerField()),
            ],
            options={
                'ordering': ['student_name', 'student_surname', 'student_number'],
            },
        ),
        migrations.CreateModel(
            name='QuizMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('which_quiz', models.CharField(choices=[('1', 'Birinci'), ('2', 'İkinci'), ('3', 'Üçüncü'), ('4', 'Dördüncü')], default='1', max_length=1)),
                ('question_number', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)])),
                ('mark', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('last_date', models.DateField(default=datetime.date(2021, 1, 18))),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuizApp.student')),
            ],
            options={
                'verbose_name': 'quiz',
                'verbose_name_plural': 'quizzes',
                'ordering': ['student', 'which_quiz', 'mark', 'last_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='quizmark',
            constraint=models.UniqueConstraint(fields=('student', 'which_quiz'), name='unique_quiz'),
        ),
    ]
